// <auto-generated />
using System;
using Luma.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luma.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602171221_AddAIReports")]
    partial class AddAIReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Luma.Api.Models.AIReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Insights")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AIReports");
                });

            modelBuilder.Entity("Luma.Api.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mood")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Luma.Api.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("ReminderTime")
                        .HasColumnType("interval");

                    b.Property<bool>("SmartRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Caffeine")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PhysicalActivityMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ScreenTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("SleepRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("StressLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SleepRecordId");

                    b.ToTable("SleepFactors");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("EfficiencyScore")
                        .HasColumnType("real");

                    b.Property<float>("QualityScore")
                        .HasColumnType("real");

                    b.Property<float>("RegularityScore")
                        .HasColumnType("real");

                    b.Property<int>("SleepDebtMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("SleepRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SleepRecordId")
                        .IsUnique();

                    b.ToTable("SleepMetrics");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SleepDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("SleepEfficiency")
                        .HasColumnType("real");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SleepDate");

                    b.ToTable("SleepRecords");
                });

            modelBuilder.Entity("Luma.Api.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Luma.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Luma.Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("PreferredSleepTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("PreferredWakeTime")
                        .HasColumnType("interval");

                    b.Property<string>("SleepGoal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Luma.Api.Models.AIReport", b =>
                {
                    b.HasOne("Luma.Api.Models.User", "User")
                        .WithMany("AIReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luma.Api.Models.NotificationSettings", b =>
                {
                    b.HasOne("Luma.Api.Models.User", "User")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Luma.Api.Models.NotificationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepFactor", b =>
                {
                    b.HasOne("Luma.Api.Models.SleepRecord", "SleepRecord")
                        .WithMany("SleepFactors")
                        .HasForeignKey("SleepRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SleepRecord");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepMetric", b =>
                {
                    b.HasOne("Luma.Api.Models.SleepRecord", "SleepRecord")
                        .WithOne("Metric")
                        .HasForeignKey("Luma.Api.Models.SleepMetric", "SleepRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SleepRecord");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepRecord", b =>
                {
                    b.HasOne("Luma.Api.Models.User", "User")
                        .WithMany("SleepRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luma.Api.Models.Subscription", b =>
                {
                    b.HasOne("Luma.Api.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Luma.Api.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luma.Api.Models.UserProfile", b =>
                {
                    b.HasOne("Luma.Api.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Luma.Api.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luma.Api.Models.SleepRecord", b =>
                {
                    b.Navigation("Metric")
                        .IsRequired();

                    b.Navigation("SleepFactors");
                });

            modelBuilder.Entity("Luma.Api.Models.User", b =>
                {
                    b.Navigation("AIReports");

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("SleepRecords");

                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
