name: sleep_analytics_mobile
description: Flutter mobile app for Sleep Analytics.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  dio: ^5.9.2
  http: ^1.6.0
  file_picker: ^8.3.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
