services:
  db:
    image: postgres:16
    container_name: luma_db
    environment:
      POSTGRES_DB: luma
      POSTGRES_USER: luma
      POSTGRES_PASSWORD: luma
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
